language: java
sudo: false
jdk:
  - oraclejdk8
service:
  - redis-server
before_script:
    - sudo redis-server /etc/redis/redis.conf --port 6379
script:
  - mvn -Dredis.manager.codec.lib.dir=${PWD}/lib/ test
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - '$HOME/.m2/repository'